### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by tapochek666** [Leapward-Koex/LockscreenGif#1]
Hi.I made an animation from frames, and when applied, the program says “failed to apply lockscreen.”

**Comment by Leapward-Koex** [comment]
I've created a new version [1.1.0](https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.1.0) with persistent logging.
Can you try again using this version then upload the .log file (e.g. app_2024-04-09.log) the new app creates on this issue and I'll see if I can figure out what's going wrong.

**Comment by tapochek666** [comment]
Hello. I tried version 1.1.0, I also had to install Desktop Runtime. The animation was applied without errors, BUT the lock screen is static, without animation, just a picture from .gif
[app_2024-04-09.log](https://github.com/Leapward-Koex/LockscreenGif/files/14917765/app_2024-04-09.log)

**Comment by Leapward-Koex** [comment]
I see the error in the logs where its failing (before its actually trying to set the gif as the lockscreen) but I'm unable to reproduce it even on a fresh Windows 11 VM.

For now I've taken a guess at a potential fix in version [1.1.1](https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.1.1). Can you try it out and get back to me with the logs if it doesn't work.

**Comment by tapochek666** [comment]
Again it was applied without errors, but the picture on win+L and after a reboot is just a static picture.
[app_2024-04-10.log](https://github.com/Leapward-Koex/LockscreenGif/files/14931731/app_2024-04-10.log)
![Буфер обмена01](https://github.com/Leapward-Koex/LockscreenGif/assets/164499068/0b70804e-a089-483b-ae87-1424ac0f127c)

**Comment by Leapward-Koex** [comment]
I managed to reproduce your issue using a non-english windows version. I have made fixes for this in version [1.2.0](https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.2.0).
Can you see if this version works for you?

**Comment by tapochek666** [comment]
It’s very strange. It says that the animation was applied normally, I didn’t see any errors in the log, but the animation is still static :(
[app_2024-04-11.log](https://github.com/Leapward-Koex/LockscreenGif/files/14945062/app_2024-04-11.log)
![Буфер обмена01](https://github.com/Leapward-Koex/LockscreenGif/assets/164499068/e35204e7-cce8-4f94-ab03-84ce556f5744)

**Comment by Leapward-Koex** [comment]
Ok I know what went wrong this time, I hadn't tested on screens <1000px tall 😅. I've made another release [1.2.1](https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.2.1) that addresses this.

**Comment by tapochek666** [comment]
Now the animation works :) All that remains is to find or make an animation yourself to suit your screen resolution. By the way, I noticed that there is no pop-up message indicating whether the animation was applied successfully or not :( But the notification itself is in the notification center.

**Comment by Leapward-Koex** [comment]
That's good to hear👍

I'm not too concerned about the notification as long as it arrived in the notification center.

Thanks for cooperating with me to resolve these bugs!

**Comment by tapochek666** [comment]
I’m glad that I found your repository! I’m also glad that you made
amendments to it for a really working program. I couldn’t find anything on
the Internet to make an animated lock screen for Windows 11. Although now
my animation weighs 34 MB, it doesn’t slow down .This is good. But, I
think, the notification needs to be completed. And it can be launched to
the general public, for example, in the Windows store, even for a fee. :)

вс, 14 апр. 2024 г. в 18:05, Leapward-Koex ***@***.***>:
