### ISSUE TITLE
Failing to set lockscreen gif

### ISSUE THREAD

**Issue by SantaSpeen** [Leapward-Koex/LockscreenGif#3]
Log:
[app_2024-11-14.log](https://github.com/user-attachments/files/17747253/app_2024-11-14.log)
Gif:
[lcwall.gif](https://github.com/user-attachments/assets/fc7b06b0-224f-4b8f-a31b-f1961e331371)

**Comment by Leapward-Koex** [comment]
The logs look like they might be from an older version. Just checking, are you running the latest version of the app? (1.2.3) https://github.com/Leapward-Koex/LockscreenGif/releases/tag/1.2.3

**Comment by SantaSpeen** [comment]
yep, it's work now
previously, the application (1.2.3) just hung up, so I downloaded an earlier version
